"""vote

Revision ID: 220cc39fd24b
Revises: 32d81cb73031
Create Date: 2022-10-23 13:58:59.938831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220cc39fd24b'
down_revision = '32d81cb73031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['t_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_votes')
    # ### end Alembic commands ###
